@startuml
!define LIGHTGREEN #c5e1a5
!define LIGHTBLUE #b3e5fc
!define WHITE #ffffff

left to right direction

skinparam backgroundColor WHITE
skinparam usecase {
  BackgroundColor LIGHTGREEN
  BorderColor #388e3c
  FontColor #1b5e20
}

skinparam actor {
  BackgroundColor LIGHTBLUE
  BorderColor #1565c0
  FontColor #0d47a1
}

skinparam package {
  BackgroundColor #f1f8e9
  BorderColor #689f38
  FontColor #33691e
}

  actor "Segurança da Informação" as Cibersegurança
  actor "Técnico de Triagem" as Tecnico
  actor "Professor" as Instrutor
  actor "Manutenção" as Manutenção
  actor "Entidade Beneficiária" as Entidade

package "G.S.E.I - Gestão Sustentável de Equipamentos" {

  ' Dashboard Use Cases
  usecase "alterar o status do produto" as UC01
  usecase "cadastrar produto" as UC02
  usecase "solicitar substituição de peças" as UC03
  usecase "definir destino final" as UC04
  usecase "registrar peças reaproveitadas" as UC05

  ' Inventory Use Cases
  usecase "solicitar o produto" as UC06
  usecase "confirmar recebimento" as UC07

  ' Triage Use Cases
  usecase "criptografar dados para descarte do produto" as UC08
  usecase "retirar unidade de armazenamento" as UC09

  ' Donation Use Cases
  usecase "Descartar o produto" as UC10
  usecase "Consertar o produto" as UC11

  ' Disposal Use Cases
  usecase "Reaproveitar o produto p/ aulas" as UC12

  ' Actor associations
  Tecnico -- UC01
  Tecnico -- UC02
  Tecnico -- UC03
  Tecnico -- UC04
  Tecnico -- UC05

  Entidade -- UC06
  Entidade -- UC07

  Cibersegurança -- UC08

  Manutenção -- UC10
  Manutenção -- UC11

  Instrutor -- UC12

  ' Includes and Extends
  UC09 <.. UC08 : <<extend>>
}

@enduml
