@startuml
!define LIGHTGREEN #c5e1a5
!define LIGHTBLUE #b3e5fc
!define WHITE #ffffff

left to right direction

skinparam backgroundColor WHITE
skinparam usecase {
  BackgroundColor LIGHTGREEN
  BorderColor #388e3c
  FontColor #1b5e20
}

skinparam actor {
  BackgroundColor LIGHTBLUE
  BorderColor #1565c0
  FontColor #0d47a1
}

skinparam package {
  BackgroundColor #f1f8e9
  BorderColor #689f38
  FontColor #33691e
}

  actor "Técnico de Informática" as Tecnico
  actor "Usuário da instituição" as usuario
  actor "Entidade Beneficiária" as Entidade
  actor "Administrador" as ADM

package "G.S.E.I - Gestão Sustentável de Equipamentos" {

  ' Técnico de Informática
  usecase "Disponibilizar equipamento" as UC01
  usecase "Cadastrar equipamento" as UC04
  usecase "Definir destino final" as UC03

  ' Entidade Beneficiária
  usecase "Cadastrar no sistema" as UC04
  usecase "Pesquisar equipamentos" as UC05
  usecase "Solicitar o equipamento" as UC06

  ' Usuário da instituição
  usecase "Abrir a chamada" as UC07

  ' ADM
  usecase "Confirmar retirada" as UC08
  usecase "Aprovar entidade beneficiária" as UC09
  usecase "Aprovar doação" as UC10

  ' Actor associations
  Tecnico -- UC01
  Tecnico -- UC02
  Tecnico -- UC03

  Entidade -- UC04
  Entidade -- UC05
  Entidade -- UC06

  usuario -- UC07

  ADM -- UC08
  ADM -- UC09
  ADM -- UC10
}

@enduml
