@startuml
!define LIGHTGREEN #c5e1a5
!define LIGHTBLUE #b3e5fc
!define WHITE #ffffff

left to right direction

skinparam backgroundColor WHITE
skinparam usecase {
  BackgroundColor LIGHTGREEN
  BorderColor #388e3c
  FontColor #1b5e20
}

skinparam actor {
  BackgroundColor LIGHTBLUE
  BorderColor #1565c0
  FontColor #0d47a1
}

skinparam package {
  BackgroundColor #f1f8e9
  BorderColor #689f38
  FontColor #33691e
}

  actor "Administrador" as ADM

package "G.S.E.I - Gestão Sustentável de Equipamentos" {

  usecase "Visualizar dashboard" as UC02
  usecase "Cadastrar equipamento" as UC03
  usecase "Gerir status" as UC08
  usecase "Definir destino final" as UC05
  usecase "Ir para descarte" as UC11
  usecase "Gerar relatórios" as UC14
  usecase "Definir destino final" as UC04
  usecase "Cadastrar entidade beneficiária no sistema" as UC04
  usecase "Checar inventário" as UC10
  usecase "Acessar logs" as UC06
  usecase "Buscar produtos" as UC07
  usecase "Acessar controle de triagem" as UC09
  usecase "Filtrar equipamentos" as UC12
  usecase "Analisar doações" as UC13

  ADM -- UC02
  ADM -- UC10
  ADM -- UC04
  ADM -- UC05
  ADM -- UC09
  ADM -- UC13

  UC10 .> UC03 : <<extend>>
  UC10 .> UC08 : <<extend>>

  UC02 .> UC06 : <<extend>>
  UC02 .> UC07 : <<extend>>

  UC05 .> UC11 : <<extend>>

  UC09 .> UC12 : <<extend>>

  UC05 .> UC14 : <<extend>>
}

@enduml
