CREATE TABLE "Item" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "Tipo" "CHAR(100)" NOT NULL,
  "Nome" "CHAR(100)" NOT NULL,
  "Problema" "CHAR(1)" NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "Reaproveitamento" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "id_item" INTEGER NOT NULL,
  "nome_peça" "CHAR(100)" NOT NULL,
  PRIMARY KEY ("id", "id_item")
);

CREATE TABLE "Doação" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "nome_peça" "CHAR(100)" NOT NULL,
  "Id_item" INTEGER NOT NULL,
  "destino" "CHAR(200)" NOT NULL,
  "id_reaproveitamento" INTEGER NOT NULL,
  PRIMARY KEY ("id", "Id_item", "id_reaproveitamento")
);

CREATE TABLE "Venda" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "Id_item" INTEGER NOT NULL,
  "valor" "MONEY(0,00)" NOT NULL,
  "nome_peça" "CHAR(100)" NOT NULL,
  "id_reaproveitamento" INTEGER NOT NULL,
  PRIMARY KEY ("id", "Id_item")
);

CREATE TABLE "Consertar" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "id_item" INTEGER NOT NULL,
  "nome_peça" "CHAR(100)" NOT NULL,
  PRIMARY KEY ("id", "id_item")
);

CREATE TABLE "Descartar" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "id_item" INTEGER NOT NULL,
  "nome_peça" "CHAR(100)" NOT NULL,
  PRIMARY KEY ("id", "id_item")
);

CREATE TABLE "Ensino" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "id_item" INTEGER NOT NULL,
  "id_consertar" INTEGER NOT NULL,
  PRIMARY KEY ("id", "id_item", "id_consertar")
);

COMMENT ON COLUMN "Item"."Tipo" IS 'Tipo = Periférico, reposição;';

COMMENT ON COLUMN "Reaproveitamento"."id_item" IS 'ID do Item';

COMMENT ON COLUMN "Doação"."id_reaproveitamento" IS 'ID do Reaproveitamento';

COMMENT ON COLUMN "Venda"."id_reaproveitamento" IS 'ID do Reaproveitamento';

COMMENT ON COLUMN "Consertar"."id_item" IS 'ID do Item';

COMMENT ON COLUMN "Descartar"."id_item" IS 'ID do Item';

COMMENT ON COLUMN "Ensino"."id_item" IS 'ID do Item';

ALTER TABLE "Reaproveitamento" ADD FOREIGN KEY ("id") REFERENCES "Doação" ("id_reaproveitamento") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Consertar" ADD FOREIGN KEY ("id_item") REFERENCES "Item" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Item" ADD FOREIGN KEY ("id") REFERENCES "Descartar" ("id_item") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Reaproveitamento" ADD FOREIGN KEY ("id") REFERENCES "Venda" ("id_reaproveitamento") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Ensino" ADD FOREIGN KEY ("id_consertar") REFERENCES "Consertar" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Item" ADD FOREIGN KEY ("id") REFERENCES "Ensino" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Doação" ADD FOREIGN KEY ("Id_item") REFERENCES "Item" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Item" ADD FOREIGN KEY ("id") REFERENCES "Venda" ("Id_item") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Item" ADD FOREIGN KEY ("id") REFERENCES "Reaproveitamento" ("id_item") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Item" ADD FOREIGN KEY ("id") REFERENCES "Ensino" ("id_item") DEFERRABLE INITIALLY IMMEDIATE;
